--- Dockerfile.mingw	2020-04-29 15:20:40.017104700 +0800
+++ Dockerfile.mingw_x64	2020-04-29 16:53:12.061442800 +0800
@@ -11,12 +11,12 @@
 # $ sudo docker cp $id:/aria2/src/aria2c.exe <dest>
 # $ sudo docker rm -v $id
 
-FROM ubuntu:19.04
+FROM ubuntu:18.04
 
 MAINTAINER Tatsuhiro Tsujikawa
 
 # Change HOST to x86_64-w64-mingw32 to build 64-bit binary
-ENV HOST i686-w64-mingw32
+ENV HOST x86_64-w64-mingw32
 
 # It would be better to use nearest ubuntu archive mirror for faster
 # downloads.
@@ -106,6 +106,9 @@
         LIBS="-lws2_32" && \
     make install
 ADD https://api.github.com/repos/aria2/aria2/git/refs/heads/master version.json
-RUN git clone https://github.com/aria2/aria2 && \
-    cd aria2 && autoreconf -i && ./mingw-config && make && \
+RUN git clone -b release-1.35.0 https://github.com/aria2/aria2 && \
+    cd aria2 && \
+    patch -Np1 < ../aria2-fast.patch && \
+    autoreconf -i && ./mingw-config && make && \
     $HOST-strip src/aria2c.exe
     
